CREATE TABLE IF NOT EXISTS laps (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  game TEXT NOT NULL,
  n TEXT NOT NULL,
  t REAL NOT NULL,
  d INTEGER NOT NULL,
  ip TEXT
);
CREATE INDEX IF NOT EXISTS laps_game_t ON laps (game, t);
CREATE INDEX IF NOT EXISTS laps_ip_d ON laps (ip, d);
