name = "redline-leaderboard"
main = "worker.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "redline-leaderboard"
database_id = "3f7fb945-793d-494b-a949-fab1b2ce1b00"
